<?php
declare(strict_types=1);
$crmTitle='Promosi';
$search=trim((string)($_GET['q']??''));
$halaqoh=$_GET['halaqoh']??[]; if(!is_array($halaqoh))$halaqoh=$halaqoh!==''?[$halaqoh]:[];
$halaqoh=array_values(array_filter(array_map('trim',$halaqoh)));
$status=trim((string)($_GET['status']??'proses'));
$pembayaran=trim((string)($_GET['pembayaran']??''));
$halaqohList=[];$r=$conn->query("SELECT DISTINCT halaqoh FROM peserta WHERE halaqoh IS NOT NULL AND halaqoh<>'' ORDER BY halaqoh");
if($r)while($row=$r->fetch_assoc())$halaqohList[]=(string)$row['halaqoh'];
$where=["p.nowa IS NOT NULL","p.nowa<>''"];$params=[];$types='';
if($search!==''){$where[]="p.nama_lengkap LIKE ?";$params[]='%'.$search.'%';$types.='s';}
if($halaqoh){$ph=implode(',',array_fill(0,count($halaqoh),'?'));$where[]="p.halaqoh IN ($ph)";$params=array_merge($params,$halaqoh);$types.=str_repeat('s',count($halaqoh));}
if(in_array($status,['proses','selesai'],true)){$where[]="p.status=?";$params[]=$status;$types.='s';}
$sql="SELECT p.id,p.nama_lengkap,p.nowa,p.halaqoh,p.status,CASE WHEN MAX(pemb.id) IS NULL THEN 0 ELSE 1 END AS sudah_bayar FROM peserta p LEFT JOIN pembayaran pemb ON p.id=pemb.peserta_id WHERE ".implode(' AND ',$where)." GROUP BY p.id,p.nama_lengkap,p.nowa,p.halaqoh,p.status";
if($pembayaran==='lunas')$sql.=" HAVING sudah_bayar=1";elseif($pembayaran==='belum_lunas')$sql.=" HAVING sudah_bayar=0";
$sql.=" ORDER BY CASE WHEN UPPER(TRIM(p.halaqoh)) LIKE 'AK%' THEN 1 WHEN UPPER(TRIM(p.halaqoh)) LIKE 'IK%' THEN 2 ELSE 3 END, CAST(SUBSTRING(TRIM(p.halaqoh),3) AS UNSIGNED), p.halaqoh, p.nama_lengkap LIMIT 200";
$peserta=[];$stmt=$conn->prepare($sql);
if($stmt){if($params){$refs=[];foreach($params as $k=>$v)$refs[$k]=&$params[$k];call_user_func_array([$stmt,'bind_param'],array_merge([$types],$refs));}$stmt->execute();$peserta=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();}
$previousMessages=[];$r=$conn->query("SELECT message,COUNT(*) usage_count,MAX(sent_at) last_used_at FROM crm_message_history WHERE template_name='Promosi' AND status='sent' AND message<>'' GROUP BY message ORDER BY last_used_at DESC LIMIT 20");
if($r)while($row=$r->fetch_assoc())$previousMessages[]=$row;
function promosiTime(string $v):string{$t=strtotime($v);return $t?date('d M Y, H:i',$t):'-';}
?>
<section class="reminder-promosi-page">
<div class="reminder-promosi-back"><a href="?page=reminder" aria-label="Kembali"><i class="fa-solid fa-arrow-left"></i></a></div>
<div class="reminder-promosi-head"><div><span class="reminder-kicker">Workspace</span><h1>Promosi</h1><p>Broadcast gambar dan pesan ke peserta yang dipilih.</p></div><div class="reminder-promosi-safety"><i class="fa-solid fa-shield-halved"></i> Pengiriman bertahap</div></div>
<div class="reminder-promosi-grid"><main>
<section class="reminder-card"><div class="reminder-card-head"><div><span class="reminder-kicker">Audience</span><h2>Pilih Penerima</h2></div><span class="reminder-count"><?=count($peserta)?> peserta</span></div>
<form method="GET" class="reminder-promosi-filter"><input type="hidden" name="page" value="reminder-promosi"><input type="search" name="q" value="<?=htmlspecialchars($search)?>" placeholder="Cari nama peserta...">
<select name="status"><option value="proses" <?=$status==='proses'?'selected':''?>>Status: Proses</option><option value="selesai" <?=$status==='selesai'?'selected':''?>>Status: Selesai</option><option value="semua" <?=$status==='semua'?'selected':''?>>Semua Status</option></select>
<select name="pembayaran"><option value="">Semua Pembayaran</option><option value="lunas" <?=$pembayaran==='lunas'?'selected':''?>>Lunas</option><option value="belum_lunas" <?=$pembayaran==='belum_lunas'?'selected':''?>>Belum Lunas</option></select><button><i class="fa-solid fa-filter"></i> Filter</button>
<details class="reminder-promosi-halaqoh"><summary><?= $halaqoh?count($halaqoh).' halaqoh dipilih':'Semua Halaqoh' ?><i class="fa-solid fa-chevron-down"></i></summary><div class="reminder-promosi-halaqoh-menu"><?php foreach($halaqohList as $h):?><label><input type="checkbox" name="halaqoh[]" value="<?=htmlspecialchars($h)?>" <?=in_array($h,$halaqoh,true)?'checked':''?>> <?=htmlspecialchars($h)?></label><?php endforeach;?></div></details></form>
<div class="reminder-promosi-selectbar"><label><input type="checkbox" id="selectAllPromosi"> Pilih semua hasil filter</label><span id="selectedPromosiCount">0 dipilih</span></div>
<?php if(!$peserta):?><div class="reminder-empty">Tidak ada peserta yang sesuai dengan filter.</div><?php else:?><div class="reminder-list reminder-promosi-list"><?php foreach($peserta as $p):?><label class="reminder-person reminder-promosi-person"><span class="reminder-target"><input type="checkbox" class="promosi-checkbox" value="<?=intval($p['id'])?>" data-name="<?=htmlspecialchars($p['nama_lengkap'],ENT_QUOTES)?>"><span class="reminder-avatar"><?=htmlspecialchars(strtoupper(substr(trim($p['nama_lengkap']),0,1)))?></span></span><span class="reminder-person-body"><strong><?=htmlspecialchars($p['nama_lengkap'])?></strong><small><?=htmlspecialchars($p['nowa'])?> · <?=htmlspecialchars($p['halaqoh'])?></small></span><span class="reminder-person-status <?=$p['sudah_bayar']?'paid':'unpaid'?>"><?=$p['sudah_bayar']?'Lunas':'Belum Lunas'?></span></label><?php endforeach;?></div><?php endif;?></section>
<section class="reminder-card reminder-promosi-history"><div class="reminder-card-head compact"><div><span class="reminder-kicker">Riwayat</span><h2>Pesan Sebelumnya</h2></div><span class="reminder-count"><?=count($previousMessages)?> pesan</span></div><?php if(!$previousMessages):?><div class="reminder-empty compact">Belum ada pesan yang dikirim.</div><?php else:?><div class="reminder-previous-list"><?php foreach($previousMessages as $m):?><article class="reminder-previous-item"><p><?=nl2br(htmlspecialchars($m['message']))?></p><div class="reminder-previous-meta"><span><?=$m['usage_count']?>x dipakai · <?=htmlspecialchars(promosiTime($m['last_used_at']))?></span><button type="button" class="use-promosi-message" data-message="<?=htmlspecialchars($m['message'],ENT_QUOTES)?>">Gunakan Lagi</button></div></article><?php endforeach;?></div><?php endif;?></section>
</main>
<aside class="reminder-promosi-side"><section class="reminder-card reminder-compose-card"><div class="reminder-card-head"><div><span class="reminder-kicker">Campaign</span><h2>Buat Promosi</h2></div><span class="reminder-wa-icon"><i class="fa-brands fa-whatsapp"></i></span></div>
<form id="reminderPromosiForm" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=htmlspecialchars(crmCsrfToken())?>">
<div class="reminder-field"><label for="promosiImage">Gambar</label><input type="file" id="promosiImage" accept="image/jpeg,image/png,image/gif" required><span class="reminder-helper">JPG, PNG, GIF · maksimal 5 MB.</span></div>
<div class="reminder-field"><label for="promosiCaption">Caption</label><textarea id="promosiCaption" maxlength="2000" required placeholder="Assalamualaikum, Kak {nama}..."></textarea><div class="reminder-message-meta"><span>{nama} diganti otomatis.</span><span id="promosiCharCount">0 / 2000</span></div></div>
<div class="reminder-field"><label for="promosiLink">Tautan <span>(opsional)</span></label><input type="url" id="promosiLink" maxlength="500" placeholder="https://..."></div>
<div class="reminder-promosi-preview"><div class="reminder-promosi-preview-head"><span class="reminder-avatar">J</span><div><strong>Jawwada Tahfidz</strong><small>online</small></div></div><div class="reminder-promosi-bubble"><div class="reminder-promosi-image" id="promosiPreviewImage"><i class="fa-regular fa-image"></i><span>Preview gambar</span></div><p id="promosiPreviewText">Caption akan muncul di sini...</p><small>10:00</small></div></div>
<div class="reminder-promosi-selected" id="promosiSelectedPreview">Belum ada penerima yang dipilih.</div>
<div class="reminder-promosi-send-info"><i class="fa-solid fa-circle-info"></i><span>Jeda 8–15 detik antar pesan dan cooldown 2 menit tiap 15 pesan.</span></div>
<button type="submit" class="reminder-send-btn" id="sendPromosiBtn" disabled><i class="fa-solid fa-paper-plane"></i> Mulai Campaign</button></form></section>
<section class="reminder-card reminder-promosi-progress" id="promosiProgressCard" hidden><div class="reminder-card-head compact"><div><span class="reminder-kicker">Progress</span><h2 id="promosiProgressTitle">Menyiapkan...</h2></div><span id="promosiProgressCount" class="reminder-count">0 / 0</span></div><div class="reminder-progress-track"><span id="promosiProgressBar"></span></div><p id="promosiProgressStatus">Menyiapkan campaign.</p><div class="reminder-progress-stats"><span>✓ <b id="promosiSuccess">0</b></span><span>× <b id="promosiFailed">0</b></span><span>◷ <b id="promosiRemaining">0</b></span></div></section></aside></div></section>
<script>
(()=>{const form=document.getElementById('reminderPromosiForm'),checks=[...document.querySelectorAll('.promosi-checkbox')],all=document.getElementById('selectAllPromosi'),count=document.getElementById('selectedPromosiCount'),selected=document.getElementById('promosiSelectedPreview'),send=document.getElementById('sendPromosiBtn'),img=document.getElementById('promosiImage'),cap=document.getElementById('promosiCaption'),link=document.getElementById('promosiLink'),chars=document.getElementById('promosiCharCount'),pimg=document.getElementById('promosiPreviewImage'),ptext=document.getElementById('promosiPreviewText'),card=document.getElementById('promosiProgressCard'),title=document.getElementById('promosiProgressTitle'),pc=document.getElementById('promosiProgressCount'),bar=document.getElementById('promosiProgressBar'),stat=document.getElementById('promosiProgressStatus'),ok=document.getElementById('promosiSuccess'),fail=document.getElementById('promosiFailed'),left=document.getElementById('promosiRemaining');
function items(){return checks.filter(x=>x.checked).map(x=>({id:+x.value,name:x.dataset.name||''}))}
function sync(){const s=items();count.textContent=s.length+' dipilih';send.disabled=!s.length||!cap.value.trim()||!img.files.length;if(!s.length)selected.textContent='Belum ada penerima yang dipilih.';else selected.innerHTML='<strong>'+s.slice(0,3).map(x=>x.name.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))).join(', ')+'</strong>'+(s.length>3?' +'+(s.length-3)+' lainnya':'');chars.textContent=cap.value.length+' / 2000';let t=cap.value.replace(/\{nama\}/gi,s[0]?.name||'Kak');if(link.value.trim())t+='
'+link.value.trim();ptext.textContent=t||'Caption akan muncul di sini...'}
checks.forEach(x=>x.onchange=()=>{all.checked=checks.length>0&&checks.every(c=>c.checked);sync()});all?.addEventListener('change',()=>{checks.forEach(x=>x.checked=all.checked);sync()});cap.oninput=sync;link.oninput=sync;
img.onchange=()=>{const f=img.files[0];if(!f)return;if(f.size>5242880){alert('Ukuran gambar maksimal 5 MB.');img.value='';sync();return}const r=new FileReader();r.onload=e=>pimg.innerHTML='<img src="'+e.target.result+'" alt="Preview">';r.readAsDataURL(f);sync()};
document.querySelectorAll('.use-promosi-message').forEach(b=>b.onclick=()=>{cap.value=b.dataset.message||'';sync();cap.focus()});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function uploadImage(f){const d=new FormData();d.append('csrf',form.querySelector('[name=csrf]').value);d.append('promo_image',f);const r=await fetch('actions/reminder-promosi-upload.php',{method:'POST',body:d,headers:{'X-Requested-With':'XMLHttpRequest'}});const j=await r.json().catch(()=>null);if(!r.ok||!j||j.status!=='success')throw new Error(j?.message||'Upload gambar gagal.');return j.token}
async function sendOne(item,token,isLast){const d=new FormData();d.append('csrf',form.querySelector('[name=csrf]').value);d.append('participant_id',item.id);d.append('caption',cap.value.trim());d.append('registration_link',link.value.trim());d.append('image_token',token);d.append('final_send',isLast?'1':'0');const r=await fetch('actions/reminder-promosi-send.php',{method:'POST',body:d,headers:{'X-Requested-With':'XMLHttpRequest'}});const j=await r.json().catch(()=>null);if(!r.ok||!j)throw new Error('Respons server tidak valid.');return j}
form.onsubmit=async e=>{e.preventDefault();const s=items(),f=img.files[0];if(!s.length||!f||!cap.value.trim())return;if(!confirm('Mulai campaign ke '+s.length+' penerima? Pengiriman dilakukan bertahap.'))return;card.hidden=false;send.disabled=true;[img,cap,link,all,...checks].forEach(x=>x.disabled=true);let success=0,failed=0;let token;try{stat.textContent='Mengunggah gambar sekali ke server...';token=await uploadImage(f)}catch(error){stat.textContent=error.message||'Upload gambar gagal.';send.disabled=false;[img,cap,link,all,...checks].forEach(x=>x.disabled=false);return}for(let i=0;i<s.length;i++){title.textContent='Mengirim ke '+s[i].name;pc.textContent=(i+1)+' / '+s.length;left.textContent=s.length-i;try{const j=await sendOne(s[i],token,i===s.length-1);j.status==='success'?success++:failed++;stat.textContent=j.message||'Selesai.'}catch(_){failed++;stat.textContent='Gagal memproses '+s[i].name+'.'}bar.style.width=Math.round((i+1)/s.length*100)+'%';ok.textContent=success;fail.textContent=failed;left.textContent=s.length-i-1;if(i<s.length-1){const d=8000+Math.floor(Math.random()*7001),c=(i+1)%15===0?120000:0;stat.textContent=c?'Cooldown 2 menit setelah batch.':'Jeda '+Math.ceil(d/1000)+' detik...';await sleep(d+c)}}title.textContent='Campaign selesai';stat.textContent=success+' berhasil, '+failed+' gagal.';left.textContent='0';setTimeout(()=>location.reload(),2500)};sync()})();
</script>